### ISSUE TITLE
Asciidoctor throws a warning: invalid style for listing block: ditaa

### ISSUE THREAD

**Issue by Frituurpanda** [asciidoctor/asciidoctor.js#410] opened 2018-01-15 14:57 UTC
Hello, 

I'm trying to use asciidoctor.js like defined in the spec example of Nashorn listed [here](https://github.com/asciidoctor/asciidoctor.js/blob/master/spec/nashorn/AsciidoctorConvertWithNashorn.java). Attempting this on a adoc file like for example: [Fulcro's developer guide](https://github.com/fulcrologic/fulcro/blob/develop/DevelopersGuide.adoc) gives me the following warning:

`[INFO] [talledLocalContainer] asciidoctor: WARNING: <stdin>: line 5337: invalid style for listing block: ditaa` 

for about 8 times. Due to this error it seems to run pretty slowly.

Is there anything else i'm supposed to add besides the `asciidoctor.js` file? I've basically followed the [AsciidoctorConvertWithNashorn.java](https://github.com/asciidoctor/asciidoctor.js/blob/master/spec/nashorn/AsciidoctorConvertWithNashorn.java) and [asciidoctor-convert.js
](https://github.com/asciidoctor/asciidoctor.js/blob/master/spec/nashorn/asciidoctor-convert.js) examples.

Aside from that, since i'm using Nashorn, ReferenceError: "plaform" is not defined with Nashorn #390 does not seem to be merged into the latest release v1.5.6-preview.4. Would it be possible to do a new release with this fixed included in it?

**Comment by Mogztter** [comment] 2018-01-15 16:15
Hello @Frituurpanda !

> [INFO] [talledLocalContainer] asciidoctor: WARNING: <stdin>: line 5337: invalid style for listing block: ditaa

Since Asciidoctor Diagram is not available in Asciidoctor.js, we cannot render `ditaa` diagram. I bielieve this is the reason why we are issuing these warnings.

> Due to this error it seems to run pretty slowly.

I don't think these warnings are causing performance issues. However the document has 57 includes and for each include we are doing an I/O (which can slow down the rendering).

> Is there anything else i'm supposed to add besides the asciidoctor.js file? I've basically followed the AsciidoctorConvertWithNashorn.java and asciidoctor-convert.js
examples.

No, you should be fine, the document should be rendered (without the `ditaa` diagrams) ?

> Aside from that, since i'm using Nashorn, ReferenceError: "plaform" is not defined with Nashorn #390 does not seem to be merged into the latest release v1.5.6-preview.4. Would it be possible to do a new release with this fixed included in it?

Indeed, this fix is not yet available in a release. :disappointed_relieved: 
We are actively working on the 1.5.6 "final" version but I might release a "preview.5" with this bugfix.

**Comment by Frituurpanda** [comment] 2018-01-15 22:30
Hey @Mogztter! 

Thanks for the fast response!

The document is indeed rendered without the `ditaa` diagrams. When observing the output it only seems to hang on printing those lines, maybe it might indeed be hanging on those 57 includes..

It would be amazing if there could be an intermediate preview version if that won't take up to much of your time! I'll be looking forward to the next 1.5.6 version.

Thanks for your great work!

**Comment by Mogztter** [comment] 2018-01-28 18:00
> It would be amazing if there could be an intermediate preview version if that won't take up to much of your time! I'll be looking forward to the next 1.5.6 version.

The intermediate preview version is here!
Version [1.5.6-preview.5](https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.6-preview.5) is available 🎉

**Comment by Mogztter** [comment] 2018-02-10 16:53
@Frituurpanda I can confirm that the Nashorn engine is way slower (especially on the first run).

Here's the time taken to render the [AsciiDoc user manual](https://raw.githubusercontent.com/asciidoc/asciidoc/d43faae38c4a8bf366dcba545971da99f2b2d625/doc/asciidoc.txt):

```
$ node build/benchmark/node.js
Load scripts: 0.214s
Run #1: 0.81s
Run #2: 0.677s
Run #3: 0.574s
Run #4: 0.542s
```
```
$ jjs build/benchmark/nashorn.js
Load scripts: 3.243s
Run #1: 15.444s
Run #2: 5.34s
Run #3: 4.089s
Run #4: 3.348s
```

You can run the benchmark from the master branch with the command `yarn run benchmark node` and `yarn run benchmark jjs`. *Note: you can use `npm` instead of `yarn`*.

**Comment by Frituurpanda** [comment] 2018-02-11 15:34
Hi @Mogztter,

Excuses for not responding to your last message, I did not set the notifications quite right. Thanks heaps for releasing the 1.5.6-preview.5! This will help me a lot to start with. 

Interesting indeed that it's slower. The pattern does indeed correspond with what i'm seeing on my own tests. Firstly i thought it slowed down because of the ditaa related error but that does not seem to be the case.

Do you have any lead on why it's slower on the Nashorn engine?

**Comment by Mogztter** [comment] 2018-02-11 16:19
JavaScript V8 engine is highly optimized. I'm sure the Nashorn team is working hard to improve the performance but currently V8 is just much faster.
Also keep in mind that the code of Asciidoctor.js is generated from Ruby code.

On the JVM you can run [AsciidoctorJ](https://github.com/asciidoctor/asciidoctorj) (a Java binding using JRuby), the performance might be better 😉 

Hopefully, with Java 9 or 10, the Nashorn engine will be considerably faster ⚡️

**Comment by Mogztter** [comment] 2018-07-28 16:55
I'm closing this issue since there's nothing we can do about Nashorn performance.
Also there's a JEP to deprecate Nashorn in Java 11: http://openjdk.java.net/jeps/335

We may look at alternatives:

* https://github.com/ringo/ringojs
* https://www.graalvm.org

**Closed by Mogztter** 2018-07-28 16:55 UTC
Labels: :thinking: clarification
