### ISSUE TITLE
Reused externalized footnotes are duplicated

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor.js#1154] opened 2020-11-24 01:36 UTC
An example copied-and-pasted from the user manual:

> **[61.1. Externalizing a Footnote](https://asciidoctor.org/docs/user-manual/#externalizing-a-footnote)**
>
>```
>:fn-hail-and-rainbow: footnote:[The double hail-and-rainbow level makes my toes tingle.]
>:fn-disclaimer: footnote:disclaimer[Opinions are my own.]
>
>The hail-and-rainbow protocol can be initiated at five levels:
>double, tertiary, supernumerary, supermassive, and apocalyptic party.{fn-hail-and-rainbow}
>A bold statement!{fn-disclaimer}
>
>Another outrageous statement.{fn-disclaimer}
>```

Asciidoctor Ruby:

> ![fn2](https://user-images.githubusercontent.com/18004961/100034704-d486f900-2e0d-11eb-91eb-9b84b72c30c4.PNG)

Chrome and Firefox extensions:

> ![fn1](https://user-images.githubusercontent.com/18004961/100034739-e8325f80-2e0d-11eb-8be8-2ec0217577e9.PNG)

The reused footnote is unexpectedly duplicated.

**Comment by mojavelinux** [comment] 2020-11-24 02:32
@Mogztter I'm thinking maybe this is due to a regexp incompatibility. However, that's just a hunch. I haven't dug into it.

**Comment by Mogztter** [comment] 2020-11-25 20:38
Thanks for your report @john-cj 
I will add a test case to reproduce this issue and identify the root cause.

**Comment by Mogztter** [comment] 2020-11-25 20:55
Actually it was fixed in Asciidoctor (Ruby) 2.0.11. I can reproduce this issue when Asciidoctor.js is built against Asciidoctor (Ruby) 2.0.10 but it's working as expected with Asciidoctor (Ruby) >= 2.0.11.

**Comment by mojavelinux** [comment] 2020-11-25 20:59
Aha! I had made the assumption Asciidoctor.js was building against 2.0.12. Good detective work.

**Comment by Mogztter** [comment] 2020-11-25 21:06
Not yet but I'm working on it :wink: 
I've backported a few changes on the 2.x branch and will release a new version based on 2.0.12 relatively soon.

**Comment by Mogztter** [comment] 2020-11-26 18:26
Fix available in https://github.com/asciidoctor/asciidoctor.js/releases/tag/v2.2.1

**Closed by Mogztter** 2020-11-26 18:26 UTC
Labels: :bug: bug

**Comment by mojavelinux** [comment] 2020-11-26 19:08
Thanks @Mogztter!
