### ISSUE TITLE
Relative includes does not work in webpack

### ISSUE THREAD

**Issue by Hanterdro** [asciidoctor/asciidoctor.js#381] opened 2017-09-15 07:30 UTC
The include syntax does not work in Webpack.

I'm using the asciidoctor-loader (https://github.com/exaptis/asciidoctor-loader) for the webpack integratoin.

Please add an example how includes should work.

**Webpack 3.4.0 config**
```js
    rules: [
        {
            test: /\.adoc/,
            use: [
                {
                    loader: "html-loader"
                },
                {
                    loader: "asciidoctor-loader",
                    options: {
                        attributes: 'showtitle'
                    }
                }
            ]

        }
    ]
```

**File: src/adoc/foobar.adoc**
```
= Hello,  World

include test

include::foo.adoc[]
```

**File: src/adoc/foo.adoc**
```
content of foo
```

**File: src/js/app.js**
 ```js
import content from '../adoc/foobar.adoc';
document.querySelector('body').innerHTML = content;
```

**Error:**
```
    ERROR in ./src/adoc/foobar.adoc
    Module build failed: Error: ENOENT: no such file or directory, open 'foo.adoc'
        at Object.fs.openSync (fs.js:652:18)
        at $File.ːinitialize [as $initialize] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:20294:40)
        at singleton_class_alloc.TMP_4 [as $new] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/opal-runtime/src/opal.js:3139:23)
        at $PreprocessorReader.ːopen [as $open] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:20254:45)
        at $PreprocessorReader.ːpreprocess_include [as $preprocess_include] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31684:86)
        at $PreprocessorReader.ːprocess_line [as $process_line] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31380:36)
        at $PreprocessorReader.ːpeek_line [as $peek_line] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:30986:41)
        at $PreprocessorReader.ːpeek_line [as $peek_line] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31411:129)
        at $PreprocessorReader.ːskip_blank_lines [as $skip_blank_lines] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31099:41)
        at singleton_class_alloc.ːnext_section [as $next_section] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:28673:16)
        at singleton_class_alloc.ːnext_section [as $next_section] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:28633:23)
        at singleton_class_alloc.ːparse [as $parse] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:28479:21)
        at $Document.ːparse [as $parse] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:27419:32)
        at module_constructor.ːload [as $load] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:33226:65)
        at module_constructor.ːconvert (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:33306:20)
        at module_constructor.Opal.Asciidoctor.$$class.$$proto.convert (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:33455:21)
        at Object.module.exports (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/index.js:20:22)
     @ ./src/js/app.js 3:0-43
```

If I use an absolute path for the include it works:
```
include::/Users/pizza/asciidoc-test/src/adoc/foo.adoc[]
```

I think the `require('fs').openSync` function in `asciidoctor.js` has the wrong path working space.
```js
      if ($scope.get('JAVASCRIPT_IO_MODULE')['$==']("node")) {
        return self.fd = require('fs').openSync(path, flags)
        } else {
        return nil
      };
```

**Comment by Mogztter** [comment] 2017-09-15 07:41
Hello @Hanterdro 

It may be related to https://github.com/asciidoctor/asciidoctor.js/issues/379 ? What version of Asciidoctor.js are you using ?

**Comment by Hanterdro** [comment] 2017-09-15 07:42
The webpack-loader uses
    "asciidoctor.js": "1.5.5-4"

**Comment by Hanterdro** [comment] 2017-09-15 14:30
I fixed it in the webpack loader (see my pull request https://github.com/exaptis/asciidoctor-loader/pull/5). I still think this is a bug in asciidocotor.js, but through my bugfix the `include::[]` is resolved by webpack, which means other webpack loaders can be used in asciidoc files. This is cool, I can now include a grahviz file in an asciidoc file :)

**Comment by Mogztter** [comment] 2017-09-15 15:54
> I fixed it in the webpack loader (see my pull request exaptis/asciidoctor-loader#5). 

Cool :+1: 

>  I still think this is a bug in asciidocotor.js, but through my bugfix the include::[] is resolved by webpack, which means other webpack loaders can be used in asciidoc files. This is cool, I can now include a grahviz file in an asciidoc file :)

@Hanterdro Did you try to configure the `base_dir` ? http://asciidoctor.org/docs/user-manual/#ruby-api-options

What was the `path` in `return self.fd = require('fs').openSync(path, flags)` ?

**Comment by Hanterdro** [comment] 2017-09-18 15:11
@Mogztter 

`path` returns the value of the `include` statement.

`include::./foo.adoc[]` would return in `path` the value `./foo.adoc`.

I don't think that `base_dir` will help, because if a static base_dir is set require will still get the wrong path, because `path` has to be reative to the file which contains the  `include` statement.

**Comment by Mogztter** [comment] 2017-09-23 13:39
> However, my pull request in the webpack-loader has a workaround for this issue. I did implement the include syntax additional in the webpack-loader, so asciidoctor will get only files without includes :-)
Webpack resolves the relative path out of the box correct and other webpack-loaders are working through the include statement.

Ok.
I still this should work out of the box, I will try to create a simple test case to reproduce this issue.

**Comment by Mogztter** [comment] 2018-07-29 10:06
> I think this should work out of the box, I will try to create a simple test case to reproduce this issue.

Looking at it again, I'm not sure about what I said (ie. "it should work out of the box").

The [Asciidoctor Loader for Webpack](https://github.com/exaptis/asciidoctor-loader) does have the [context](https://github.com/exaptis/asciidoctor-loader/pull/5/files#diff-168726dbe96b3ce427e7fedce31bb0bcR25) to resolve the path. On the contrary Asciidoctor.js does not know how to resolve the relative path because this dynamic information is missing.

@Hanterdro I think your fix is the way to go. You could also replace the include directive path with an absolute path and let Asciidoctor.js resolve/include the file:

```adoc
include::foo.adoc[]
```


```adoc
include::/path/to/foo.adoc[]
```

Anyway I'm closing this issue since I (now) think that the fix should be in the [Asciidoctor Loader for Webpack](https://github.com/exaptis/asciidoctor-loader).

Thanks for your report and your fix @Hanterdro :+1:

**Closed by Mogztter** 2018-07-29 10:06 UTC
