### ISSUE TITLE
Using 'coderay' or 'pygments' crashes asciidoctor.js

### ISSUE THREAD

**Issue by nerk** [asciidoctor/asciidoctor.js#95] opened 2015-01-01 19:33 UTC
Executing the following code snippet with node.js produces an exception. The problem seems to be that specifying source-highlighter as either 'coderay' or 'pygments' tries to execute this highlighter, which is, of course, not available in a JavaScript environment.

However, setting source-highlighter to something completely unknown like 'xxx' simply ignores source highlighting and does not crash asciidoctor.js.

Maybe a warning should be issued if an unknown source highlighter is used or if a known highlighter is not available in the current environment?

```
var asciidoctor = require('asciidoctor.js')();
var opal = asciidoctor.Opal;

var  processor = asciidoctor.Asciidoctor(true);


var content = '= Test\n'
+ ':source-highlighter: coderay\n\n'    // <== modify here
+ '[source, xml]\n'
+ '----    \n'
+ '<?xml-stylesheet href="style.css" type="text/css"?>\n'
+ '<?xml-stylesheet href="print.css" media="print" type="text/css"?>\n'
+ '----\n';

console.log(content);

var attributes = 'source-highlighter=highlight.js@';
var options = opal.hash2(
    ['doctype', 'safemode', 'header_footer', 'attributes'],
    {'doctype': 'article', 'safemode': 'unsafe', 'header_footer': true, 'attributes': attributes});

var html = processor.$convert(content, options);
console.log(html);
```
Exception:

```
/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2438
      throw exception;
            ^
NameError: uninitialized constant Object::CodeRay
    at OpalClass.def.$backtrace.self [as $new] (/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2783:17)
    at OpalClass.def.$raise (/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2434:31)
    at OpalClass.def.$const_missing (/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:1351:19)
    at Opal.cm (/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:480:22)
    at h.k.$highlight_source (/usr/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:3:11939)
    at /usr/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:2:8925
    at f._isBoolean.f._isBoolean.f._p.j (/usr/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:2:9197)
    at Opal.$yield1 (/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:584:14)
    at Array.def.$each.TMP_6 [as $each] (/usr/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:5803:27)
    at h.k.$apply_subs (/usr/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:2:9214)
```

~

**Comment by nerk** [comment] 2015-01-01 19:39
There is another weird thing with the code above. I could not get the 'source-highlighter' attribute in the text processed by asciidoctor.js at all without explicitly passing a default setting in the options hash.

It worked after adding 
```
var attributes = 'source-highlighter=highlight.js@';
```

**Comment by mojavelinux** [comment] 2015-01-01 23:55
This is a known issue in the Asciidoctor.js environment atm. It's necessary to work around it with additional logic atm. You can see this logic implemented in docgist:

https://github.com/asciidoctor/docgist/blob/master/js/docgist.js#L31

Basically, you want to peek at what the user set, clear the attribute so it doesn't affect core and take whatever action you want to take to enable or disable highlighting.

```
var attributes = 'source-highlighter=highlight.js@';
```

This is the correct way to provide a default yet allow it to be overridden. Of course, if you allow it to be overridden, then you have to handle values that Asciidoctor.js doesn't support (coderay, pygments, etc) and reset the attribute before the convert phase.

I do have plans to make the source highlighter fail gracefully inside of core. See https://github.com/asciidoctor/asciidoctor/issues/1253.

**Comment by nerk** [comment] 2015-01-02 15:47
@mojavelinux Thanks, the gist helped. I am now trying to reset the highlighter to 'highlight.js' after doc.$load() as follows:
```
doc.$set_attribute('source-highlighter', 'highlight.js');
html = doc.$convert();
```
$set_attribute returns true for success, but $convert still throws the same exception because it seems to ignore the changed attribute and still uses 'coderay'. Using doc.$delete_attribute('source-highlighter') does not seem to work either.

Maybe I'm doing something wrong. I'm not a Ruby programmer and only best guessing how to use it from JavaScript by looking at the Ruby source. ;-)

**Comment by nerk** [comment] 2015-01-02 17:41
It looks as if $convert() always invokes 'restore_attributes' and overrides modified attributes with their initial values.

**Comment by mojavelinux** [comment] 2015-01-02 18:56
Yes, this is a tricky (aka rough) part of that API. Some rework is
necessary.

Until then, I think you have to use a more low-level call to change the
value to work around restore_attributes. In other words, you have to trick
it into doing what you want.

I'll file an issue for 1.5.3 to have a better API here.

**Comment by mojavelinux** [comment] 2015-01-03 00:37
Here's the related issue.

https://github.com/asciidoctor/asciidoctor/issues/1255

For now, you can directly manipulate the internal `original_attributes` property, if you can sort out how to access it from JavaScript.

Another option, which comes with some overhead, is to load the document with the `parse_header_only` option set...then read the value of the `source-highlighter` attribute. Then, run `convert()`, passing in the `source-highlighter` attribute that you want. This gives you the opportunity to "peek" at the document-level attributes before running `convert()`. I use this technique here: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/spine_item_processor.rb#L19

**Comment by nerk** [comment] 2015-01-16 20:55
I'll wait until the issue is fixed. I actually figured out how to modify `original_attributes` from JavaScript. If `source-highlighter` was not defined at all, or if it was set to `highlightjs` or `prettify`, changing `source-highlighter` to a different value by modifying `original_attributes` works as expected. 

However, if `source-highlighter` is `coderay` or `pygments`, changing it to one of the client-side renderers in `original_attributes` crashes the conversion process. It seems that  the parsed document contains some state information which is not compatible with client renderers in this case.

**Comment by mojavelinux** [comment] 2015-01-19 01:30
Technically the original_attributes is not a public API, so I would expect some oddness. Of course, it points out the need for a public API here. It wasn't something we originally considered, which is why it's a bit awkward right now.

**Comment by mojavelinux** [comment] 2015-10-13 04:54
In the change that is being proposed for 1.5.3 (see https://github.com/asciidoctor/asciidoctor/pull/1511), `restore_attributes` will be called immediately after parse. That means that after you load the document, the attributes will be:

a) the attributes as defined at the end of the header (or those overridden by the API)
b) the attributes will be modifiable

I did, however, change the internal name from `original_attributes` to `header_attributes` to be communicate the intent, but you should no longer need to access that internal state.

**Comment by nerk** [comment] 2015-10-15 14:11
:+1: Thanks!

**Comment by Mogztter** [comment] 2015-11-04 19:11
@nerk Could you please test with the latest release `1.5.3.preview.2` ?

**Comment by nerk** [comment] 2015-11-04 22:50
With `1.5.3.preview.2` I cannot set attributes at all, see #96

**Comment by mojavelinux** [comment] 2015-11-04 23:47
Here's the proper way to do this with Asciidoctor 1.5.3.

```js
var asciidoctor = require('asciidoctor.js')();
var opal = asciidoctor.Opal;
var processor = asciidoctor.Asciidoctor(true);
var content = '= Document Title\n'
+ ':source-highlighter: coderay\n\n'
+ '[source, xml]\n'
+ '----\n'
+ '<?xml-stylesheet href="style.css" type="text/css"?>\n'
+ '<?xml-stylesheet href="print.css" media="print" type="text/css"?>\n'
+ '----';

var attrs = opal.hash({'linkcss': '', 'copycss!': ''});
var options = opal.hash({'doctype': 'article', 'safe': 'safe', 'header_footer': true, 'attributes': attrs});

var doc = processor.$load(content, options);
doc.$set_attribute('source-highlighter', 'highlight.js');
var html = doc.$convert();

console.log(html);
```

That's if you want to respect the user's setting to enable source highlighting. If you just want to override what the user has and force syntax highlighting to be on, then just hard set the attribute in the attributes option:

```js
var attrs = opal.hash({'source-highlighter': 'highlight.js', 'linkcss': '', 'copycss!': ''});
```

**Comment by nerk** [comment] 2015-11-10 14:21
@mojavelinux Your example works with Asciidoctor.js 1.5.3.preview.4. However, if you modify your document by inserting an additional blank line after the document title

```
var content = '= Document Title\n\n'
+ ':source-highlighter: coderay\n\n'
+ '[source, xml]\n'
+ '----\n'
+ '<?xml-stylesheet href="style.css" type="text/css"?>\n'
+ '<?xml-stylesheet href="print.css" media="print" type="text/css"?>\n'
+ '----';
```

The output is 
```
=u.get("RuntimeError").$new(a):a.$$is_class&&(a=a.$new(b)),i["!"]=a,a}),a.defn
                                                                    ^
NameError: uninitialized constant Object::CodeRay
    at c.$new (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:2:9812)
    at null.<anonymous> (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:2:5726)
    at m.$const_missing (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:1:15941)
    at y.get (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:1:3719)
    at j.$highlight_source (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:10:16212)
    at C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:9:11235
    at h.$$is_boolean.h.$$is_boolean.h.$$p.l (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:9:11509)
    at y.yield1 (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:1:6007)
    at Array.N.$each.v [as $each] (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:3:19865)
    at j.$apply_subs (C:\Users\thomas.kern\spielwiese\adoc\asciidoctor-all.min.js:9:11527)
```

**Comment by Mogztter** [comment] 2015-11-10 21:19
> However, if you modify your document by inserting an additional blank line after the document title

I think that if you insert an additional blank line `:source-highlighter: coderay` is no longer an header attribute but a document attribute (i.e. attribute defined in the content of the document).

So `highlight.js` is used until the parser read `:source-highlighter: coderay` (and Coderay doesn't work in Asciidoctor.js therefore an exception is thrown)

I think this is the expected behavior.

**Comment by nerk** [comment] 2015-11-10 22:46
I am not sure if this should be expected behavior. I think Asciidoctor.js should rather issue a warning, ignore this setting (because it does not apply to the JavaScript environment) and continue the conversion. The current behavior makes it hard if not impossible for applications like preview plugins to deal with such a situation. What would regular users do with such an error message?

**Comment by nerk** [comment] 2015-11-10 22:50
And yes, the additional blank line makes this a document attribute. That's what I wanted to test, :wink:

**Comment by nawroth** [comment] 2015-11-11 00:18
Simply adding `Opal.CodeRay = function(){};` gives a different error, so we might be able to patch this with a fake object from the JS side. Manipulating the Ruby source would be a cleaner solution for sure.

I'm having the same issue in DocGist, I just didn't realize it until now!
Header attributes are easy enough to handle (and override as needed).
But those defined in the document can currently only be handled by enforcing a highlighter that will always be used, which I wouldn't like to do.

**Comment by Mogztter** [comment] 2015-11-11 10:19
> I am not sure if this should be expected behavior. I think Asciidoctor.js should rather issue a warning, ignore this setting (because it does not apply to the JavaScript environment) and continue the conversion. The current behavior makes it hard if not impossible for applications like preview plugins to deal with such a situation. What would regular users do with such an error message?

You can use `coderay-unavailable` attribute, see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb#L1403.

```ruby
var attrs = opal.hash({'source-highlighter': 'highlight.js', 'linkcss': '', 'copycss!': '', 'coderay-unavailable': ''});
```

**Comment by nerk** [comment] 2015-11-11 10:39
Thanks, I did not know this attribute! Generation does not crash anymore.

However, the generated HTML still contains the Coderay related markup. I would prefer a fallback to highlight.js. The user should be informed that something did not work as expected. He will just see an unstyled listing of source code.

```
<pre class="CodeRay highlight"><code data-lang="xml">&lt;?xml-stylesheet href="style.css" type="text/css"?&gt;
&lt;?xml-stylesheet href="print.css" media="print" type="text/css"?&gt;</code></pre>
```

**Comment by nerk** [comment] 2015-11-11 10:50
I just noticed that it actually works with highlight.js, probably because of `class="highlight"` matches. The following won't work, though:

```
= Test
:coderay-unavailable:
:source-highlighter: prettify

:source-highlighter: coderay

[source,javascript]
----
function asUrl(message) {
        var matches = message.match(/\s[0-9]+:\s/);
        
    }
----

```

No crash, no highlighting, no warning/error message.

**Comment by nawroth** [comment] 2015-11-11 20:49
Wow, the `unavailble` attributes for `coderay` and `pygments` are really useful! Thanks @Mogztter 

Here's what I'm doing in DocGist (in my fork for now):
* If coderay/pygments are defined in the header, override it using the default highlighter in DocGist (currently highlightjs, but I'm considering going with codemirror instead). Log a message in the console.
* Scan the content for pre.CodeRay/pre.pygments and set up the css classes to work with the different supported highlighters in case coderay/pygments were set in the document somewhere.

Trying out the example from @nerk above:
http://nawroth.github.io/docgist/?0bc953891a87e7a0b571

**Comment by mojavelinux** [comment] 2015-11-14 12:36
> I think that if you insert an additional blank line :source-highlighter: coderay is no longer an header attribute but a document attribute 

Exactly, though I would probably describe it as "a document-level attribute in the body" (as opposed to a document-level attribute in the document header, or header attribute).

**Comment by mojavelinux** [comment] 2015-11-14 12:38
> Scan the content for pre.CodeRay/pre.pygments and set up the css classes to work with the different supported highlighters in case coderay/pygments were set in the document somewhere.

I think the approach should be that you determine what the value should be prior to conversion, lock the attribute, then convert. Locking the attribute will prevent it from being changed once conversion starts. That way, it doesn't matter what crazy values are set in the document further down.

**Comment by Mogztter** [comment] 2015-11-14 13:23
> Obviously, we still need to improve the usability of the APIs around document-level attributes and locking attributes, but that's for 1.6.0

I'm moving this issue to the 1.6.0 milestone and will proceed with 1.5.3 release

**Comment by nawroth** [comment] 2015-11-14 16:22
@mojavelinux That's what I tried first, but it failed due to buggy attribute-handling code on my side. I've fixed that now, so it's back on the right track again!

**Comment by nerk** [comment] 2015-11-14 18:54
Should we close this issue and link to #140?

**Comment by Mogztter** [comment] 2015-11-14 20:48
> Obviously, we still need to improve the usability of the APIs around document-level attributes and locking attributes, but that's for 1.6.0

After reading https://github.com/asciidoctor/asciidoctor/issues/1255 I think we can already "lock" (force) an attribute in 1.5.3 with:
```ruby
doc.set_attr 'uri', 'https://google.com', true
```

> Should we close this issue and link to asciidoctor/asciidoctor#1575

Yes we can even if this one is a bit different because in the end we just want to be able to "lock" the attribute.

**Closed** 2015-11-14 21:05 UTC
Labels: upstream
