### ISSUE TITLE
NilClass_alloc { '$$id': 4, apply: [Function], call: [Function] }

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#201] opened 2016-08-17 16:42 UTC
This node.js script generates this exception `NilClass_alloc { '$$id': 4, apply: [Function], call: [Function] }` when the content is coming from a file and no stack trace is available

```javascript
var asciidoctor = require('asciidoctor.js')();
var fs = require('fs')

var opal = asciidoctor.Opal;
var processor = null;
var useExtensions = true;

if (useExtensions) {
    processor = asciidoctor.Asciidoctor(true);
}
else {
    processor = asciidoctor.Asciidoctor();
}

// Check if the path of the file to be converted is passed as parameter
if (process.argv[2]) {
    readFile(process.argv[2]);
} else {
    console.error("Please pass as parameter the path to the html file to be converted !")
}

function readFile(path) {
    var content = fs.readFileSync(path, 'utf8')
    convertToHtml(content);
}


function convertToHtml(content) {
    //console.log(content);
    var options = opal.hash({doctype: 'inline', attributes: ['showtitle']});
    try {
        var html = processor.$convert(content, options);
        console.log(html);
    } catch (e) {
        console.error(e.stack);
    }
}
```

How can we get the stack trace and more info about the error ?

**Comment by Mogztter** [comment] 2016-08-17 17:26
Hello @cmoulliard 

This is not an exception, in fact `NilClass_alloc` is the object returned by `processor.$convert(content, options);`.

In Ruby, the method should return a `Nil` instance translated by Opal to a `NilClass_alloc` instance.

The problem is that `inline` document type can only convert a single paragraph. To convert a document you need to use an `article` document type (this is the default value).
You can read more about document types here: http://asciidoctor.org/docs/user-manual/#document-types

Here's an updated version of the `convertToHtml` function:
```javascript
function convertToHtml(content) {
    var options = opal.hash({attributes: ['showtitle']});
    try {
        var html = processor.$convert(content, options);
        console.log('html', html);
    } catch (e) {
        console.error('error', e.stack);
    }
}
```

**Comment by mojavelinux** [comment] 2016-08-17 17:28
>  NilClass_alloc is the object returned by processor.$convert(content, options);.

I don't think that's correct. `$convert_file` returns nil because it directs the output to the file, but `$convert` should return the String that is converted.

**Comment by Mogztter** [comment] 2016-08-17 17:48
`$convert` method returns the String that is converted when the content is a single paragraph otherwise the method returns a `Nil` object.
But maybe we do have a different behavior on Asciidoctor core (Ruby) ?

```javascript
var options = opal.hash({doctype: 'inline', attributes: ['showtitle']});
var content = '= Title\n\n== Title 1\n\nHello world';
var html = processor.$convert(content, options);
console.log('html', html); // prints html { '$$id': 4, apply: [Function], call: [Function] }
```

```javascript
var options = opal.hash({doctype: 'inline', attributes: ['showtitle']});
var content = '*Hello world*';
var html = processor.$convert(content, options);
console.log('html', html); // prints html <strong>Hello world</strong>
```

**Comment by mojavelinux** [comment] 2016-08-17 17:49
> $convert method returns the String that is converted when the content is a single paragraph otherwise the method returns a Nil object.

Oh, yes. In that case, you are absolutely correct.

**Comment by Mogztter** [comment] 2016-08-17 20:47
I think we should really think about adding a warning in core :smile: 
https://github.com/asciidoctor/asciidoctor.js/issues/175#issuecomment-180739105

I also need to update the documentation in Asciidoctor.js to explain the limitation of `doctype: inline` and explain how to convert a document with `doctype: article`.

**Comment by mojavelinux** [comment] 2016-08-17 21:09
I agree a warning in core is appropriate. Having said that, I don't think anyone should be using the inline doctype unless that person knows what they are doing. It's not a "normal" doctype but a special API option.

**Comment by mojavelinux** [comment] 2016-09-16 03:15
@Mogztter I think part of the problem we're running into here is that the samples in the README specify the inline doctype. We know that most people just copy and paste the examples to try them out, but of course go on to use that code for converting a full document. I think we should not specify the doctype by default in the samples, and perhaps only mention the inline doctype in a dedication section with an explanation of its purpose.

**Comment by Mogztter** [comment] 2016-09-16 09:30
@mojavelinux Indeed, I've opened a pull request to simplify examples. In a second time I will add more use cases on the user manual: https://github.com/asciidoctor/asciidoctor.js/blob/master/manual.adoc

**Comment by mojavelinux** [comment] 2016-09-16 09:59
I'll also mention that there's a bunch of fun examples from the chronicles example in the Asciidoctor PDF repository. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/examples/chronicles-example.adoc

**Comment by Mogztter** [comment] 2016-09-16 15:47
> Come on, Bier Central. Did you have to ask? If you beat me there, I’ll take a St. Bernardus Abt 12.

looooool :beers:

**Comment by mojavelinux** [comment] 2016-09-16 20:48
:beers:

**Comment by Mogztter** [comment] 2016-10-09 13:18
Done https://github.com/asciidoctor/asciidoctor/issues/1890

**Comment by Mogztter** [comment] 2016-10-30 15:13
I think we can close this issue since the documentation was updated and we now return an empty string when using the wrapper API (see #252)

**Closed by Mogztter** 2016-10-30 15:13 UTC
Labels: clarification, documentation
