### ISSUE TITLE
global object detection may not work in web worker

### ISSUE THREAD

**Issue by ZeekoZhu** [asciidoctor/asciidoctor.js#942] opened 2020-04-24 07:32 UTC
I'm using asciidoctor.js with webpack in web worker, and the global object detection in `@asciidoctor/core/dist/browser/asciidoctor.js` doesn't work.

```js
  var global_object = this, console;

  // Detect the global object
  if (typeof(global) !== 'undefined') { global_object = global; }
  if (typeof(window) !== 'undefined') { global_object = window; }
```

`window` is not avaliable in web worker environment, `globalThis` and `self` could be alternatives.

**Comment by Mogztter** [comment] 2020-04-25 23:52
I believe that you are referring to this Opal code: https://github.com/opal/opal/blob/974940e43bcb609e544815609dd1db433afe5dd5/opal/corelib/runtime.js#L18-L20
The master branch is now also using `globalThis`, see: https://github.com/opal/opal/blob/master/opal/corelib/runtime.js

We planned to upgrade to the latest version of Opal but that will require a major bump at it will break the compatibility: https://github.com/asciidoctor/asciidoctor.js/pull/763

Is that blocking? Do you have an error? Can you still use Asciidoctor.js is this context? Did you find a workaround?

**Comment by ZeekoZhu** [comment] 2020-04-26 11:35
I use webpack to bundle my code, when it running in web worker, `Opal is undefined` is thrown. For now, I have to exclude asciidoctor.js from bundled result, and use `importScripts` to load `asciidoctor.min.js` into web worker.

**Comment by Mogztter** [comment] 2020-04-26 12:03
Ok, thanks for your follow-up :+1:

**Comment by Mogztter** [comment] 2020-06-27 17:12
@ZeekoZhu Could you please provide a simple reproduction case? I want to make sure that this issue is fixed on the future release. Thanks!

**Comment by ZeekoZhu** [comment] 2020-06-28 15:28
[asciidoctor-webpack.zip](https://github.com/asciidoctor/asciidoctor.js/files/4842482/asciidoctor-webpack.zip)

@Mogztter When creating this reproduction, I found that angular-cli set `node: false` in webpack config, which disabled the webpack buildin `global`. The buildin global.js created by webpack uses `Function`'s constructor to get `global` object, Asciidoctor.js works well with it, but this may violate CSP/unsafe-eval property

**Comment by Mogztter** [comment] 2020-06-28 16:25
Thanks for the reproduction case, I will take a look.

> When creating this reproduction, I found that angular-cli set node: false in webpack config, which disabled the webpack buildin global. 

Since you are targeting the browser (and more specifically web worker) I think it makes sense to set `node: false`. 

> The buildin global.js created by webpack uses Function's constructor to get global object, Asciidoctor.js works well with it, but this may violate CSP/unsafe-eval property

Interesting... maybe Webpack is using some kind of polyfill to resolve the global object in a Web worker environment (and not just the `global` object available in Node.js: https://nodejs.org/api/globals.html#globals_global)

> but this may violate CSP/unsafe-eval property

Not sure about that but yes using `globalThis` is probably a safer/future-proof choice :)

**Comment by Mogztter** [comment] 2020-06-29 07:45
Yay! I can confirm that this issue is fixed on master:

```
Running in worker,  <div class="paragraph">
<p><strong>bold</strong></p>
</div>
```

It was fixed in https://github.com/asciidoctor/asciidoctor.js/pull/763 and will be part of Asciidoctor.js 3.0.0.

**Closed** 2020-07-01 12:49 UTC
Labels: :bug: bug, :upside_down_face: upstream
