### ISSUE TITLE
ArgumentError: illegal key name: block_terminates_paragraph

### ISSUE THREAD

**Issue by brlafreniere** [asciidoctor/asciidoctor.js#141] opened 2015-11-26 04:14 UTC
ArgumentError: illegal key name: block_terminates_paragraph
        at OpalClass.$new (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2783:17)
        at OpalModule.def.$raise (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2434:31)
        at OpalModule.$define (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:5996)
        at /home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:6233
        at /home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:6601
        at /home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:31491
        at Object.Asciidoctor (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:31548)
        at Object.exports.convert (/home/blaine/projects/crisp-wiki/asciidoc.js:11:33)
        at /home/blaine/projects/crisp-wiki/index.js:14:25
        at Layer.handle [as handle_request] (/home/blaine/projects/crisp-wiki/node_modules/express/lib/router/layer.js:95:5)

Not sure exactly what's going on here, but thought I'd post it.

Thanks.

**Comment by mojavelinux** [comment] 2015-11-26 16:43
I wonder if this relates to the Opal 0.8 upgrade. We had a problem with the ordering of a constant assignment in another place in the code, so perhaps we're seeing something similar.

Are you just running Asciidoctor.js or are you trying to assign that key?

**Comment by brlafreniere** [comment] 2015-11-26 16:46
I'm not trying to assign `block_terminates_paragraph` specifically, just trying to do pretty simple stuff, render a basic inline document.

**Comment by mojavelinux** [comment] 2015-11-26 16:48
Could you post a snippet just in case it helps with debugging? I'm looking in particular for the simplest thing that makes it fail. That way, we can convert it to a test.

**Comment by brlafreniere** [comment] 2015-11-26 16:51
Here's a gist: https://gist.github.com/brlafreniere/f96989f5ab3095564f33

**Comment by brlafreniere** [comment] 2015-11-26 17:12
Also, just a note... it renders correctly the first time, but then the error appears after I refresh the page. So it always works on the first page load, then after that, the error appears.

**Comment by mojavelinux** [comment] 2015-11-27 18:44
I wonder if this happens when the new `Opal.require` method is called twice. Just brainstorming.

**Comment by mojavelinux** [comment] 2015-12-09 07:44
The illegal key name happens if the main Asciidoctor.js code is loaded more than once (same for the Ruby code). This is the first failure condition it hits when that is the case, though I should probably remove it so it's just a warning.

What I can't figure out is how the code is being loaded twice. It's not the require statement. It must literally be duplicated in the source file. Perhaps somewhere in your compilation you are getting duplicate source code somehow.

**Comment by mojavelinux** [comment] 2015-12-09 08:02
I went ahead and made a patch to core so this won't be a problem in 1.5.4. However, I still recommend tracking down why you are getting duplicate source code (at least, I'm assuming that's the cause).

**Comment by Mogztter** [comment] 2016-01-16 13:44
Hopefully resolved with the first RC of Asciidoctor.js 1.5.4 in cb68894

@brlafreniere Feel free to reopen if that's not the case.

**Closed by Mogztter** 2016-01-16 13:44 UTC
Labels: upstream
