### ISSUE TITLE
Parsing an inline link causes processor to crash for certain matches

### ISSUE THREAD

**Issue by rwinch** [asciidoctor/asciidoctor.js#1732] opened 2024-05-23 18:00 UTC
When using asciidoctor.js 2.2.7

I create an (invalid) index.adoc file as show below

```asciidoc
= Heading

<<https://example.com,Example Link>>
```

I get the following error:

```
./node_modules/asciidoctor/bin/asciidoctor --version              
Asciidoctor.js 2.2.7 (Asciidoctor 2.0.22) [https://asciidoctor.org]
Runtime Environment (node v18.13.0 on linux)
CLI version 3.5.0
./node_modules/asciidoctor/bin/asciidoctor index.adoc --stacktrace

/home/rwinch/code/rwinch/asciidoctor-error/node_modules/asciidoctor-opal-runtime/src/opal.js:2476
        return $$($nesting, 'TypeError').$new("" + "no implicit conversion of " + (object.$class()) + " into " + (type))
                                         ^
constructor [TypeError]: no implicit conversion of NilClass into String
    at Function.$$type_error (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/asciidoctor-opal-runtime/src/opal.js:2476:42)
    at Function.$$coerce_to (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/asciidoctor-opal-runtime/src/opal.js:2487:26)
    at String.$String_$plus$7 (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/asciidoctor-opal-runtime/src/opal.js:6516:36)
    at $rb_plus (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:3226:90)
    at $$34 (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:3884:24)
    at String.$$gsub (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/asciidoctor-opal-runtime/src/opal.js:7048:26)
    at Opal.send (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
    at constructor.$$sub_macros (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:3876:18)
    at /home/rwinch/code/rwinch/asciidoctor-error/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:3321:66
    at $$2 (/home/rwinch/code/rwinch/asciidoctor-error/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:3329:91)

Node.js v18.13.0
```

The latest 3.x asciidoctor.js and asdiidoctor (Ruby) do not fail.

I first noticed this problem when using Antora (which uses asdiidoctor.js 2.x line) in Spring Batch (see the [build](https://github.com/spring-projects/spring-batch/actions/runs/9078858058/job/24946792255#step:5:3892)). It took a lot of effort to track this down. Generally, the failure and error message are very difficult to debug. It would be nice if this were handled in a way that made it easier to solve.

**Comment by mojavelinux** [comment] 2024-05-23 18:10
This is the same issue as https://github.com/asciidoctor/asciidoctor/issues/4570 and has been fixed in the upstream.

The xref shorthand you showed is not technically valid. That's requesting that the target of an internal xref be a URL, which doesn't make any sense. I'm curious where you are getting this syntax from.

**Comment by ggrossetie** [comment] 2024-05-23 18:11
I believe this issue has been fixed upstream: https://github.com/asciidoctor/asciidoctor/issues/4570

We need to release a new Asciidoctor.js version based on Asciidoctor (Ruby) 2.0.28.

This error in Java would be a NullPointerException and since the JavaScript code is transpiled from Ruby it does not make it easier to decipher.
Having said that, Asciidoctor maintainers can relatively easily find the root cause with this stacktrace (and fix the underlying bug).

**Comment by ggrossetie** [comment] 2024-05-23 18:36
Yep, 2.0.23! Sorry I'm on mobile and I mixed up the numbers 🫠

**Comment by mojavelinux** [comment] 2024-05-28 07:42
I did some more thinking about this and I've come to realize that there is more we can do in Antora to improve the log message when a situation like this occurs. I've opened the following issue to track this improvement: https://gitlab.com/antora/antora/-/issues/1123 Let's continue the discussion there as it pertains to Antora.

**Comment by ggrossetie** [comment] 2024-06-02 08:38
Asciidoctor.js 2.2.8 is out, could you please try again?

**Comment by mojavelinux** [comment] 2024-06-02 09:36
I verified the fix and added a test to Antora for it.

**Closed** 2024-06-03 17:17 UTC
Labels: :bug: bug, :upside_down_face: upstream
