### ISSUE TITLE
Use asciidoctor.js in Vite with react

### ISSUE THREAD

**Issue by Wegt-meoh** [asciidoctor/asciidoctor.js#1671] opened 2022-11-22 06:13 UTC
```tsx
import "./App.css";
import asciidoctor from "asciidoctor";
const asciiDoc = asciidoctor();

function App() {
  return <div className="App"></div>;
}

export default App;
```

it thows:
```
Uncaught TypeError: Cannot assign to read only property 'length' of function 'function() {
          var block2 = alias.$$p, args2, i, ii;
          args2 = new Array(arguments.length);
   ...<omitted>... }'
    at Opal2.alias (asciidoctor.js:1869:11)
    at asciidoctor.js:2809:10
    at Opal.modules.corelib/module (asciidoctor.js:3558:3)
    at Opal2.load (asciidoctor.js:2314:7)
    at Opal2.require (asciidoctor.js:2342:17)
    at Opal.modules.opal/base (asciidoctor.js:5469:8)
    at Opal2.load (asciidoctor.js:2314:7)
    at Opal2.require (asciidoctor.js:2342:17)
    at asciidoctor.js:20069:8
    at node_modules/@asciidoctor/core/dist/browser/asciidoctor.js (asciidoctor.js:20079:1)
```

**Comment by Mogztter** [comment] 2022-11-22 18:22
That's a duplicate of https://github.com/asciidoctor/asciidoctor.js/issues/686
The current version of Opal (used by Asciidoctor 2.x) does not support strict mode hence the error.

I will be fixed in Asciidoctor 3.x.

**Closed by Mogztter** 2022-11-22 18:22 UTC
