### ISSUE TITLE
Asciidoctor() is not a function

### ISSUE THREAD

**Issue by Kikketer** [asciidoctor/asciidoctor.js#269] opened 2016-11-22 17:53 UTC
Super basic:

```javascript
var asciidoctor = require('asciidoctor.js')();
var processor = asciidoctor.Asciidoctor();
```

It's throwing an exception:
```
var processor = asciidoctor.Asciidoctor();
                            ^
TypeError: asciidoctor.Asciidoctor is not a function
```

Inspection of the asciidoctor object gives me lots of things, but no `Opal` or `Asciidoctor`:
```
console.dir(asciidoctor.Opal);  // undefined
console.dir(asciidoctor.Asciidoctor); // undefined
console.dir(asciidoctor.Parser); // singleton_class_alloc { .. lots of goodies }
```

It's been installed `npm install --save asciidoctor.js`.  The folder exists under node_modules, and is version `"version": "1.5.5-4"`

I'm using node: `v6.9.1` on a macbook.

**Comment by mojavelinux** [comment] 2016-11-22 18:26
I believe this has to do with the unification of the API. See https://github.com/asciidoctor/asciidoctor.js/issues/225. I'm not sure if the README reflects this change yet.

**Comment by Kikketer** [comment] 2016-11-22 18:38
Thanks but even the "current" isn't working for me.  Has there been changes already?
```javascript
var asciidoctor = require('asciidoctor.js')();

var processor = null;
var useExtensions = true;

if (useExtensions) {
  processor = asciidoctor.Asciidoctor(true);
}
else {
  processor = asciidoctor.Asciidoctor();
}

var html = processor.convert('abcde');
console.log(html);
```
ERROR:
```
  processor = asciidoctor.Asciidoctor(true);
                          ^
TypeError: asciidoctor.Asciidoctor is not a function
```

And attempted with:
```javascript
var Asciidoctor = require('asciidoctor.js'); // with extensions by default
// var Opal = require('opal-runtime'); // (optional if needed)

var html = Asciidoctor.convert(content);
console.log(html); 
```

Error (which is obvious since #225 isn't in place yet):
```
var html = Asciidoctor.convert('abcde');
                       ^
TypeError: Asciidoctor.convert is not a function
```

**Comment by Kikketer** [comment] 2016-11-22 19:38
Reverting to `1.5.5-3` has fixed the issue, so it is something with new new code in `-4`

**Comment by gravitycode** [comment] 2016-12-14 13:39
some news?

**Comment by Mogztter** [comment] 2016-12-22 18:23
Hello @Kikketer 

@mojavelinux is right, this is breaking chance caused by the unification of the API.
The code should be:

```javascript
var asciidoctor = require('asciidoctor.js')();
var content = "= My document";
var html = asciidoctor.convert(content);
console.log(html);
```

**Comment by Mogztter** [comment] 2016-12-22 20:32
@gravitycode @Kikketer I've open a pull request in asciidoctor-loader to fix this issue: https://github.com/exaptis/asciidoctor-loader/pull/3

**Comment by exaptis** [comment] 2016-12-22 21:02
@Mogztter thanks! pull-request has been merged :-)

**Comment by mojavelinux** [comment] 2016-12-23 02:10
@exaptis Interesting project!

**Comment by Mogztter** [comment] 2017-01-12 12:53
@exaptis Can I close this issue ?

**Comment by exaptis** [comment] 2017-01-12 13:15
@Mogztter yes, thanks!

**Comment by Mogztter** [comment] 2017-01-12 13:20
You're welcome 😉

**Closed by Mogztter** 2017-01-12 13:20 UTC

**Comment by thetutlage** [comment] 2017-01-27 13:29
How can minor/patch releases can contain breaking changes? Following semver will make everyones lives easily.

**Comment by Mogztter** [comment] 2017-01-27 14:07
I do agree but we (as a community) have decided to use the same version for Asciidoctor (Ruby), AsciidoctorJ (Java) and Asciidoctor.js (JavaScript)

In fact, Asciidoctor.js is generated from Asciidoctor Ruby using Opal (cross-compilation). The same goes for AsciidoctorJ where Asciidoctor Ruby is called using a JRuby binding.
I should probably state this fact in the README and encourage people to define the exact version.

**Comment by thetutlage** [comment] 2017-01-27 15:40
@Mogztter I just created a PR for same https://github.com/asciidoctor/asciidoctor.js/pull/277
