### ISSUE TITLE
Issues with resolving URI includes in asciidoc content.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.js#148] opened 2015-12-08 06:01 UTC
In https://github.com/asciidoctor/asciidoctor/issues/1599#issuecomment-162774406 I was discussing with @mojavelinux an issue I was having with getting URI includes to work.

He's confirmed that there may be an issue with using asciidoctor.js in "Browser Mode", which may be preventing the https://github.com/norganna/adoc-usermacro confluence AsciiDoc User Macro from transforming URI sourced content.

What's happening is that the macro is not including asciidoc files referenced by URIs in the expected way as described in http://asciidoctor.org/docs/user-manual/#include-content-from-a-uri. It is only rendering the URI link.

On the /master branch of https://github.com/norganna/adoc-usermacro I've specified the `allow-uri-read` attribute but the macro is still not converting includes to rendered content.

@mojavelinux quotes

```
Actually, I think your first instinct it right. 
This is a bug (or at least a deficiency) in Asciidoctor.js. I tried it from the Asciidoctor.js cli (https://github.com/asciidoctor/asciidoctor-cli.js) and it doesn't work. 
I think the Chrome extension (or the browser mode) has a configuration that is missing when running it outside the browser (but still in JavaScript). 
Likely it has something to do with this code: https://github.com/asciidoctor/asciidoctor.js/blob/master/lib/asciidoctor/opal_ext/file.rb#L102-L148
```

**Comment by mojavelinux** [comment] 2015-12-08 06:15
> He's confirmed that there may be an issue with using asciidoctor.js in "Browser Mode"

Actually, I think it's outside of browser mode that is the problem.

After looking closer at the adoc-usermacro, I realize that the problem may be that you aren't running in safe (or server) mode. You probably need to set it like:

```
options = Opal.hash({
  doctype: 'article',
  backend: 'html5',
  safe: 'safe',
  attributes: ['showtitle', 'allow-uri-read']
}),
```

Notice I removed the use of Opal.hash2. That isn't necessary.

**Comment by mojavelinux** [comment] 2015-12-08 06:15
In other words, there are two different problems (two different scenarios) here.

**Comment by jaredmorgs** [comment] 2015-12-09 00:57
@mojavelinux That fix you proposed works great for GitHub-hosted content! So it definitely has solved the issue of URI resolution. 

Now I just need to work out why Atlassian Stash URIs are not resolving.

**Comment by mojavelinux** [comment] 2015-12-09 00:59
Great news!

Let's be sure not to lose in this issue that URI includes are not resolving when using Asciidoctor.js outside the browser (as far as I have observed).

**Comment by Mogztter** [comment] 2015-12-12 17:21
The problem is that Node.js can't read remote files synchronously. The current implementation is:

```javascript
require('fs').readFileSync(path, 'utf8');
```

The above code will not work with URI.
We can use [https.get](https://nodejs.org/api/https.html#https_https_get_options_callback) but I didn't find any native solution to make it work synchronously.

@mojavelinux Do you think we can hack something on Asciidoctor core to support Async I/O ?

**Comment by mojavelinux** [comment] 2015-12-12 23:53
I'm just not sure how an async read in core would work since the parser cannot proceed without knowing the lines of content in sequence.

There are two solutions that I see for this:

1. Use an sync request library like https://github.com/ForbesLindesay/sync-request
2. Use a pre-processor step to resolve and cache the content, then invoke the converter once all the content is available

Using (2), we would scan for remote includes (perhaps using a throwaway parse step), then parse again with an include processor that returns the cached data from the URIs. In short, we'd use a custom IncludeProcessor and two passes through the parser (pass 1: collect, pass 2: use).

Since (2) is more involved, we should see how far we can get with (1) first.

**Comment by Mogztter** [comment] 2015-12-21 18:22
I think we can implement the same as [sync-request](https://github.com/ForbesLindesay/sync-request) but without external dependencies. The basic idea is to use [spawnSync](https://nodejs.org/docs/v0.12.0/api/child_process.html#child_process_child_process_spawnsync_command_args_options) to spawn a child process synchronously. This process will do an async request but the process will wait (exit) until it get a response. So basically it's a sync request.

**Comment by jaredmorgs** [comment] 2015-12-21 21:57
Definitely keen to assist with testing in any way I can.

On Tue, 22 Dec 2015 at 04:22 Guillaume Grossetie <notifications@github.com>
wrote:

> I think we can implement the same as sync-request
> <https://github.com/ForbesLindesay/sync-request> but without external
> dependencies. The basic idea is to use spawnSync
> <https://nodejs.org/docs/v0.12.0/api/child_process.html#child_process_child_process_spawnsync_command_args_options>
> to spawn a child process synchronously. This process will do an async
> request but the process will wait (exit) until it get a response. So
> basically it's a sync request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.js/issues/148#issuecomment-166381700>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment] 2015-12-21 22:21
:+1:

**Comment by mojavelinux** [comment] 2015-12-21 22:26
What would be ideal is to get this into Opal, but in the short term it makes sense to put something in place in Asciidoctor.js until that plays out.

**Comment by jaredmorgs** [comment] 2016-03-09 05:47
This is causing me the same issue for GitLab RAW content.

URL pattern on GitLab is https://example.com/docs/glossary/raw/master/Introduction.adoc and it won't load the referenced file.

**Comment by mojavelinux** [comment] 2016-03-09 06:35
@jaredmorgs Could you clarify your scenario. Are you running Asciidoctor.js on a file that has an include that points to a file on GitLab?

**Comment by jaredmorgs** [comment] 2016-03-09 09:44
It's basically the same issue with the adoc-usermacro not loading content
from a direct URL using an include statement from BitBucket Server (and
now) GitLab.

It comes down to URL structure, and how content targets in includes are
currently parsed by the .js version of the tool.

The last thing discussed was to implement a way for the links to be loaded.
On Wed, 9 Mar 2016, 16:35 Dan Allen <notifications@github.com> wrote:

> @jaredmorgs <https://github.com/jaredmorgs> Could you clarify your
> scenario. Are you running Asciidoctor.js on a file that has an include that
> points to a file on GitLab?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.js/issues/148#issuecomment-194139740>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment] 2016-03-09 10:02
The best way to proceed is that we need a test that runs either in node.js or phantomjs. @Mogztter would you be willing to help get a test setup so that we can start to talk about something tangible?

**Comment by Mogztter** [comment] 2018-07-28 17:15
I'm pretty sure we have a test, though I'm not 100% sure that the test covers your exact use case.
Could you please provide a sample document with the expected result ? 

```
= Title

== Section 1

include::https://raw.githubusercontent.com/asciidoctor/asciidoctor.js/master/README.adoc[]
```

**Comment by Mogztter** [comment] 2019-04-13 18:48
It should be resolved in Asciidoctor.js 2.0.0.
Please reopen with a reproduction case if this bug is still occurring.

**Closed by Mogztter** 2019-04-13 18:48 UTC
Labels: :doughnut: improvement
