### ISSUE TITLE
Stylesheet not used to generate the HTML

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#202] opened 2016-08-17 17:23 UTC
When I use this syntax to pass as attribute another style and dir, the HTML generated doesn't look like a foundation page

``` javascript
function convertToHtml(content) {
    var attrs = opal.hash({'showtitle' : '',
                           'stylesheet': 'foundation.css',
                           'stylesdir' : '/Users/chmoulli/Code/github/asciidoctor/asciidoctor-stylesheet-factory/stylesheets/'});
    var options = opal.hash({doctype    : 'article',
                             attributes : attrs});
    try {
        var html = processor.$convert(content, options);
        fs.writeFileSync("./generated_content/output.html", html);
    } catch (e) {
        console.error(e.stack);
    }
}
```

**Comment by Mogztter** [comment] 2016-08-17 17:38
I think you need to use `header_footer: true` otherwise you will generate an embeddable HTML (without `<head>` and `<footer>`).

```javascript
var options = opal.hash({header_footer: true, attributes : attrs});
```

You can also remove the trailing slash on `stylesdir`:

```javascript
var attrs = opal.hash({'showtitle' : '',
                       'stylesheet': 'foundation.css',
                       'stylesdir' : '/Users/chmoulli/Code/github/asciidoctor/asciidoctor-stylesheet-factory/stylesheets'});
```

**Comment by mojavelinux** [comment] 2016-08-17 17:48
@Mogztter correct. There are actually two approaches. You can either set `header_footer` to `true`, or you can set the `to_file` and let the `$convert` method handle writing to file (the latter is the preferred approach in this case).

**Comment by mojavelinux** [comment] 2016-08-17 17:49
The other reason you don't use any styles is because if you write the HTML file yourself, then Asciidoctor doesn't copy the stylesheet. Asciidoctor only copies the stylesheet when it handles writing the HTML file.

**Comment by cmoulliard** [comment] 2016-08-18 05:48
Can you document the different ways that we can use `processor.$convert()` to generate a string a response, save to a file, ... ?

**Comment by cmoulliard** [comment] 2016-08-18 06:00
If I use this syntax

```
    var attrs = opal.hash({'showtitle'  : '',
                           'stylesheet' : 'foundation',
                           'stylesdir'  : '/Users/chmoulli/Code/github/asciidoctor/asciidoctor-stylesheet-factory/stylesheets'});
    var options = opal.hash({doctype    : 'article',
                             to_dir     : '/Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/generated_content',
                             to_file    : 'output.html',
                             attributes : attrs});
    try {
        processor.$convert(content, options);
```

I get this error 

```
SecurityError: Jail is not an absolute path: .
    at SingletonClass_alloc.$new (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4512:15)
    at SingletonClass_alloc.$exception (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4530:31)
    at d.<anonymous> (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4281:31)
    at d.$system_path (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:501:479)
    at f.$normalize_system_path (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:157:423)
    at module_constructor.<anonymous> (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:646:313)
    at convertToHtml (/Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/asciidoc.js:38:19)
    at readFile (/Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/asciidoc.js:24:5)
```

**Comment by mojavelinux** [comment] 2016-08-18 08:22
You almost always want to set the safe mode. When you get errors about the jail, it means you are using the default safe mode. The recommended safe mode is either safe or unsafe.

I don't think you should be setting the doctype. That is something the document should set. (The option is provided for special uses).

**Comment by mojavelinux** [comment] 2016-08-18 08:23
> Can you document the different ways that we can use processor.$convert() to generate a string a response, save to a file, ... ?

They are the same as the Ruby API. Having said that, we are still testing all these cases in Asciidoctor.js, so you are a guinea pig / early adopter ;)

**Comment by cmoulliard** [comment] 2016-08-18 08:46
Thx. The error is gone after setting the `safe` mode. 

I'm facing this error now 

```
IOError: target directory does not exist: /Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/generated_content
    at SingletonClass_alloc.$new (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4512:15)
    at SingletonClass_alloc.$exception (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4530:31)
    at module_constructor.<anonymous> (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4281:31)
    at module_constructor.<anonymous> (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:647:385)
```

The directory exists. The error is reported by this line of code within `asciidoctor-core.js`

```
          } else if (to_file !== false && to_file !== nil) {
            outfile = doc.$normalize_system_path(to_file, working_dir, jail, $hash2(["target_name", "recover"], {"target_name": "to_dir", "recover": false}));
            outdir = Opal.get('File').$dirname(outfile);};

```

**Comment by Mogztter** [comment] 2016-10-08 14:28
@cmoulliard I didn't have the chance to look at this issue ? Did you find a workaround ? Do you have a test case so I can easily reproduce this issue ?

**Comment by Mogztter** [comment] 2018-07-28 17:08
I believe this issue is fixed in the latest version of Asciidoctor.js if it's not the case feel free to reopen it.

**Closed by Mogztter** 2018-07-28 17:08 UTC
Labels: :memo: documentation, :thinking: clarification
