### ISSUE TITLE
Override file reader

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#112] opened 2015-05-20 15:35 UTC
Hello;

When we enabled safe mode in asciidoctor.js it loads resources from rest. Is there any way to override this default behaviour ? I want to load this resource from Java call or from WebSocket.

**Comment by rahmanusta** [comment] 2015-05-20 16:48
Or can we add a query parameter or prefix to urls ??

**Comment by mojavelinux** [comment] 2015-05-20 18:44
This depends highly on the environment in which Asciidoctor.js is running. If you are running it via Nashorn, it should use the Java APIs to load the file.

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/opal_ext/file.rb#L102-L109

This isn't extensible right now, though you could cross compile an additional Ruby file and append it to Asciidoctor.js that overrides this method. Basically, just implement the method in Ruby code like this:

```ruby
class File
  def self.read path
    %x(JavaScript code goes here; path is a local JavaScript variable)
  end
end
```

Then cross compile that with Opal and add it to your asciidoctor.js file (or load it separately).

Another way to tackle the problem is to create an IncludeProcessor extension. That will take over resolving include files and you can load them however you want. You can write extensions in Ruby and cross compile or you can write them in JavaScript (though a bit more tricky).

To move this issue forward, though, I'd like to know 2 things:

1. What is the runtime environment exactly and how can we detect it in JavaScript?
2. What code do you want to use to load the file?

**Comment by rahmanusta** [comment] 2015-05-21 06:27
Hello Dan;

My environment browser but that is a embedded browser in JavaFX platform. I tried like that https://github.com/asciidocfx/asciidoctor/blob/master/lib/asciidoctor/opal_ext/file.rb#L117

It loads resources from Java method call.

For your questions;

1. Environment is embedded browser in JavaFX platform.  Maybe we can add a new environment named "afx" or "asciidocfx", it inherits browser environment behaviours but also afx spesific behaviours.

We can detect Asciidocfx platform for example in following like snippet;

````
if(app)
  if(app.platform=="asciidocfx")
````

2. https://github.com/asciidocfx/asciidoctor/blob/master/lib/asciidoctor/opal_ext/file.rb#L117

What do you think about declaring new environment for asciidocfx? 

Thank you so much.

**Comment by mojavelinux** [comment] 2015-05-21 06:42
> What do you think about declaring new environment for asciidocfx?

I'd rather that we set the JAVASCRIPT_PLATFORM to 'javafx' or something. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/opal_ext.rb

Then, we can implement an additional case in the switch statement to handle the file resolution as you'd like.

**Comment by rahmanusta** [comment] 2015-05-21 07:02
That is great for me. There is a patch for that https://github.com/asciidoctor/asciidoctor/compare/master...rahmanusta:patch-1

**Comment by mojavelinux** [comment] 2015-05-22 19:24
Could you submit this as a pull request? Also, are you going to add corresponding logic to file.rb as well?

**Comment by rahmanusta** [comment] 2015-05-23 08:02
Yes, I proposed a pull request now.

**Closed** 2015-08-02 11:29 UTC
