### ISSUE TITLE
Function.apply broken by asciidoctor

### ISSUE THREAD

**Issue by czb** [asciidoctor/asciidoctor.js#562] opened 2018-10-15 06:00 UTC
`Function.apply` is undefined after executing `asciidoctor.js@1.5.7-rc.1` -> `browser/asciidoctor.js`.

When running `https://cdnjs.cloudflare.com/ajax/libs/asciidoctor.js/1.5.5-5/asciidoctor.js`, `Function.apply` works just fine

**Comment by Mogztter** [comment] 2018-10-15 06:18
Hello @czb 

This issue is a duplicate of https://github.com/asciidoctor/asciidoctor.js/issues/556.
The next version of Asciidoctor.js should resolve this issue (it's already fixed on master).

The trick is to save and restore `Function` functions after loading Opal: https://github.com/Mogztter/opal-node-runtime/blob/master/src/index.js

Here's the upstream issue: https://github.com/opal/opal/issues/1846. Since it's not a simple fix, so I've decided to fix this issue downstream.

A new version of Asciidoctor.js is coming soon.

**Comment by Mogztter** [comment] 2018-10-26 12:49
Fixed in https://github.com/asciidoctor/asciidoctor.js/commit/da2c70cc977429c4e37a271cfee42b461c8cd422

**Closed by Mogztter** 2018-10-26 12:49 UTC
Labels: :bug:  bug, :upside_down_face: upstream

**Comment by jirutka** [comment] 2018-11-29 02:18
I'm experiencing this error after upgrading to asciidoctor.js 1.5.9 when I build (bundle) the project using Rollup. :( Opal is really PITA, I'll eventually end up with sandboxing asciidoctor.js to avoid Opal infecting the runtime.

**Comment by Mogztter** [comment] 2018-11-29 08:49
For now Opal does not have a solution, so I'm using this workaround to save and restore fundamental objects: https://github.com/Mogztter/opal-node-runtime/blob/master/src/index.js

Could you please share a reproduction case ? I'm not familiar with Rollup but I will try to setuo an integration project to reproduce this issue.
